---
name: jobs
on: 
  push:
    branches: 
    - main
    - dev
    - qa
  pull_request:
     branches: 
      - main    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: this is build job
        run: echo " this is build job"


  
